## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Kemery and Adam's Wedding!"
copyright = "2024"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"

# Local
baseURL = "/"
publishDir = "docs"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Wedding invitation website"
  # This sets the favicon to the given emoji.
  IconEmoji = "🧙‍♂️"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]

[_build]
  list = 'always'
  publishResources = true
  render = 'always'